version: "3"

services:
    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

    cache:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - cache:/data

volumes:
    mongodb_data_container:
        driver: local
    cache:
        driver: local
